blog/urls.py
from . import views
from django.urls import path

# posts urls route

urlpatterns = [
    path('', views.PostsListView.as_view(), name='posts'),
    path('<slug:slug>/', views.PostsDetailView.as_view(), name='posts_detail'),

]

simple_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# status params
STATUS = (
    (0, 'Draft'),
    (1, 'Publish'),
)


#  created models
class Posts(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    contents = models.TextField()
    created_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/views.py
from django.views import generic

# import models
from .models import Posts


# Create your views here.

class PostsListView(generic.ListView):
    queryset = Posts.objects.filter(status=1).order_by('created_on')
    template_name = 'blog/index.html'


class PostsDetailView(generic.DetailView):
    model = Posts
    template_name = 'blog/posts_detail.html'

blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title>{% block titles %} {% endblock titles %} - Simple Blog</title>
  </head>
  <body>
    {% block contents %}
    
    {% endblock contents %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- footer -->
    <footer class="py-3 bg-grey">
      <p class="m-0 text-dark text-center ">Copyright &copy; My Website</p>
  </footer>
  </body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block titles %}
    Blog
{% endblock titles %}



{% block contents %}
<link rel="stylesheet" href="{% static 'css/blog_style.css' %}">
{% include "blog/partials/navbar.html" %}

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'posts_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock contents %}

blog/templates/blog/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-darj bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'posts' %}">My Website</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'posts' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts' %}">Blog</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

blog/templates/blog/posts_detail.html
{% extends "blog/base.html" %}

{% block titles %}
  {{ object.title}}
{% endblock titles %}



{% block contents %}
{% include "blog/partials/navbar.html" %}

<div class="container">
    <div class="row">
      <div class="col-md-8 card mb-4  mt-3 left  top">
        <div class="card-body">
          <h1>{{ object.title }}</h1>
          <p class="text-muted">{{ object.author }} | {{ object.created_on }}</p>
          <p class="card-text ">{{ object.contents | safe }}</p>
        </div>
        </div>
    </div>
  </div>
{% endblock contents %}